import { ArticleFrontmatter } from '@/types/content';

/** Convert HTML content to clean Markdown/MDX text */
export function htmlToMarkdown(html: string): string {
  if (!html) return '';

  let output = html;

  // Remove <colgroup> and <col> tags generated by Tiptap table extension
  output = output.replace(/<colgroup>[\s\S]*?<\/colgroup>/gi, '');

  // Self-close void elements if any remain
  output = output
    .replace(/<col(?:\s+[^>]*[^\/])?>/gi, '')
    .replace(/<br(?:\s+[^>]*[^\/])?>/gi, '<br />')
    .replace(/<hr(?:\s+[^>]*[^\/])?>/gi, '<hr />');

  // Convert headings
  output = output
    .replace(/<h1>(.*?)<\/h1>/gi, '# $1\n\n')
    .replace(/<h2>(.*?)<\/h2>/gi, '## $1\n\n')
    .replace(/<h3>(.*?)<\/h3>/gi, '### $1\n\n')
    .replace(/<h4>(.*?)<\/h4>/gi, '#### $1\n\n')
    .replace(/<p>(.*?)<\/p>/gi, '$1\n\n')
    .replace(/<strong>(.*?)<\/strong>/gi, '**$1**')
    .replace(/<b>(.*?)<\/b>/gi, '**$1**')
    .replace(/<em>(.*?)<\/em>/gi, '*$1*')
    .replace(/<i>(.*?)<\/i>/gi, '*$1*')
    .replace(/<code>(.*?)<\/code>/gi, '`$1`')
    .replace(/<blockquote[^>]*>(.*?)<\/blockquote>/gi, '> $1\n\n')
    .replace(/<ul[^>]*>([\s\S]*?)<\/ul>/gi, (_, list) =>
      list.replace(/<li[^>]*>(.*?)<\/li>/gi, '- $1\n') + '\n'
    )
    .replace(/<ol[^>]*>([\s\S]*?)<\/ol>/gi, (_, list) =>
      list.replace(/<li[^>]*>(.*?)<\/li>/gi, '1. $1\n') + '\n'
    )
    .replace(/<a href="([^"]+)">(.*?)<\/a>/gi, '[$2]($1)')
    .replace(/<img src="([^"]+)" alt="([^"]*)"\s*\/?>/gi, '![$2]($1)\n\n')
    .replace(/<hr\s*\/?>/gi, '---\n\n')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return output;
}

/** Serialize frontmatter metadata + markdown body into MDX file text */
export function serializeMdx(
  frontmatter: ArticleFrontmatter,
  contentHtml: string
): string {
  const yamlFrontmatter = [
    '---',
    `title: "${frontmatter.title.replace(/"/g, '\\"')}"`,
    `description: "${frontmatter.description.replace(/"/g, '\\"')}"`,
    `slug: "${frontmatter.slug}"`,
    `contentType: "${frontmatter.contentType}"`,
    `topic: "${frontmatter.topic}"`,
    `tags: [${frontmatter.tags.map((t) => `"${t}"`).join(', ')}]`,
    `publishedAt: "${frontmatter.publishedAt || new Date().toISOString()}"`,
    frontmatter.updatedAt ? `updatedAt: "${frontmatter.updatedAt}"` : null,
    `draft: ${frontmatter.draft}`,
    `featured: ${frontmatter.featured}`,
    frontmatter.author ? `author: "${frontmatter.author}"` : null,
    frontmatter.cover ? `cover: "${frontmatter.cover}"` : null,
    '---',
  ]
    .filter(Boolean)
    .join('\n');

  const markdownBody = htmlToMarkdown(contentHtml);

  return `${yamlFrontmatter}\n\n${markdownBody}\n`;
}
